language: csharp
mono: none
dotnet: 1.0.1
dist: trusty

script:
  - dotnet restore sdk/AWSSDK.CoreCLR.sln
  - dotnet build sdk/AWSSDK.CoreCLR.sln
  - dotnet test --no-build sdk/test/CoreCLR/UnitTests/UnitTests.CoreCLR.csproj